---
- name: Install critical applications
  hosts: localhost
  become: yes
  
  vars:
    docker_credential_pass_url: "https://github.com/docker/docker-credential-helpers/releases/download/v0.6.4/docker-credential-pass-v0.6.4-amd64.tar.gz"
    gpg_id: "root"

  tasks:
    - name: Install dnf-plugins-core
      dnf:
        name: dnf-plugins-core
        state: latest

    - name: Add Docker repository
      command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

    - name: Remove docker systemd
      systemd:
        name: docker
        enabled: no
        state: stopped

    - name: Remove containerd systemd
      systemd:
        name: containerd
        enabled: no
        state: stopped

    - name: Remove Fedora versions of Docker
      yum:
        name: "{{ item }}"
        state: absent
      loop:
        - docker
        - docker-common
        - container-selinux
        - docker-selinux
        - docker-engine

    - name: Install Docker
      dnf:
        state: latest
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - skopeo

    - name: Create the docker group
      group:
        name: docker
        system: yes
        state: present

    - name: Add user to the docker group
      user:
        name: ss
        groups: docker
        append: yes

    - name: Write docker daemon file
      copy:
        content: |
          {
            "userns-remap": "default"
          }
        dest: /etc/docker/daemon.json
        owner: root
        group: docker
        mode: '0660'

    - name: Write docker config file
      copy:
        content: |
          {
            "credsStore": "pass"
          }
        dest: /etc/docker/config.json
        owner: root
        group: docker
        mode: '0660'


    - name: Install password manager and jq
      package:
        name:
          - pass
          - jq
        state: present

    - name: Configure docker-credential-pass
      unarchive:
        src: '{{ docker_credential_pass_url }}'
        remote_src: yes
        dest: /usr/local/bin
        attributes: '+x'
    
    - name: Configure Docker to start on boot
      systemd:
        name: docker
        enabled: yes
        state: reloaded

    - name: Configure containerd to start on boot
      systemd:
        name: containerd
        enabled: yes

    - name: Initialize pass
      become: no
      command: 'pass init {{ gpg_id }}'
