---
- name: Install OpenShift 4 binaries
  hosts: localhost
  become: yes

  tasks:
    - name: Install from dnf repository
      dnf:
        name:
          - source-to-image
          - skopeo

    - name: Fetch CodeReady Containers 
      unarchive:
        src: https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/crc/latest/crc-linux-amd64.tar.xz
        dest: /usr/local/bin
        remote_src: yes
        extra_opts:
          - '--strip-components=1'  

    - name: Cleanup CRC Install
      file:
        name: /usr/local/bin/LICENSE
        state: absent

