---
roles:
- name: gantsign.visual-studio-code
- name: tvieira.powerline-fonts
- name: geerlingguy.kubernetes
- name: geerlingguy.helm
- name: geerlingguy.pip
- name: gantsign.golang

collections:
- ansible.posix
- community.general
