---
- name: Saves secrets to file
  hosts: localhost
  tasks:
    - name: Create encrypted, password-protected private key
      raw: gpg --export-secret-keys -a -o - | gpg --output /tmp/private.key.gpg --symmetric -
