---
- hosts: localhost
  roles:
    - role: 'secrets'
      become: false
      tags:
        - sys
        - secrets
      vars:
        primary_gpg_keyid: 8859AB55ED3CEF31E9C1316A992A867530CC0D4F
        primary_ssh_keygrip: 2E5C2C9F1D68FC2827DBD52AC3CBC7A791B84DFD

# Installs builders, sdks, and other development environment stuff
      become: true
      tags: 
        - sys
      vars:

# Sets up a kubernetes+podman+oc pipeline for OpenShift 4; ideal for developers / OS4 Application Delivery specialists
# Tested on CentOS 8 Stream

    - role: 'crio'
      become: true
      tags:
        - containers
      vars: 
        crio_os: CentOS_8_Stream
        crio_version: 1.23 # Match with kubernetes

    - role: 'geerlingguy.kubernetes'
      become: true
      tags:
        - containers
      vars:
        kubernetes_version: 1.23 # Match with crio
        kubernetes_version_rhel_package: 1.23.5 # Match with crio
        kubernetes_allow_pods_on_master: true
        kubernetes_config_kubelet_configuration:
          cgroupDriver: systemd
          fail-swap-on: false

        block_devices:
          - { dir: '/var/storage', uuid: '07fed395-5daa-4800-8b87-b4f888ef3f07', type: 'data' }
          - { dir: '/var/cache', uuid: 'd6cb375e-85da-49b4-884d-a9bd21d6ebcf', type: 'cache' }

        tmpfs_devices:
          - { dir: '/tmp', size: '4g'}

    - role: containers
      become: true
      tags:
        - containers
      vars:
        primary_gpg_keyid: 8859AB55ED3CEF31E9C1316A992A867530CC0D4F
        crc_version: 1.34.0 # The expected version is defined by the vscode extension -> Add OpenShift Cluster

    - role: tvieira.powerline-fonts
      become: true
      tags:
        - fonts
      vars:
        all_users:
          - user: ss
            homedir: /home/ss
        all_fonts:
          - SourceCodePro

    - role: usr
      become: false
      tags:
        - usr
      vars:
        firefox_extensions:
          - '3872123' # Adblock Plus
          - '3910071' # Bitwarden

    - role: devtools
      become: false
      tags:
        - devtools
      vars:
        local_development_root: '/var/storage/sdg/openshift'

   
    - role: gantsign.visual-studio-code
      become: true
      tags:
        - vscode
        - devtools
      users:
        - username: "{{ ansible_user_id }}"
          visual_studio_code_extensions:
            # - 4ops.terraform
            - aaron-bond.better-comments
            # - batisteo.vscode-django
            - christian-kohler.path-intellisense
            - eamodio.gitlens
            - Equinusocio.vsc-material-theme
            - Equinusocio.vsc-material-theme-icons
            - formulahendry.code-runner
            - golang.Go
            - IBM.output-colorizer
            - mads-hartmann.bash-ide-vscode
            - mhutchie.git-graph
            - mikestead.dotenv
            - ms-azuretools.vscode-docker
            - ms-python.python
            - njpwerner.autodocstring
            - redhat.ansible
            - redhat.fabric8-analytics
            - redhat.java
            - redhat.vscode-knative
            - redhat.vscode-openshift-extension-pack
            - redhat.vscode-openshift-java-pack
            - redhat.vscode-quarkus
            - redhat.vscode-tekton-pipelines
            - redhat.vscode-yaml
            # - ritwickdey.LiveServer
            - Trunk.io
            - Tim-Koehler.helm-intellisense
            - VisualStudioExptTeam.vscodeintellicode
            - wholroyd.jinja

          visual_studio_code_settings_overwrite: yes
          visual_studio_code_settings: {
            "debug.console.fontFamily": "'MesloLGS NF'",
            "docker.host": "unix:///run/user/1000/podman/podman.sock",
            "files.autoSave": "onFocusChange",
            "editor.bracketPairColorization.enabled": true,
            "editor.guides.bracketPairs": true,
            "editor.linkedEditing": true,
            "editor.mouseWheelZoom": true,
            "editor.acceptSuggestionOnEnter": "off",
            "extensions.ignoreRecommendations": true,
            "files.insertFinalNewline": true,
            "git.alwaysSignOff": true,
            "git.autofetch": true,
            "git.closeDiffOnOperation": true,
            "git.enableCommitSigning": true,
            "git-graph.repository.commits.mute.commitsThatAreNotAncestorsOfHead": true,
            "git.postCommitCommand": "push",
            "git.showPushSuccessNotification": true,
            "git.useCommitInputAsStashMessage": true,
            "javascript.suggest.paths": false,
            "redhat.telemetry.enabled": false,
            "telemetry.telemetryLevel": "crash",
            "terminal.integrated.allowChords": false,
            "terminal.integrated.defaultProfile.linux": "zsh",
            "terminal.integrated.fontFamily": "'MesloLGS NF'",
            "terminal.integrated.fontSize": 13,
            "terminal.integrated.minimumContrastRatio": 7,
            "terminal.external.linuxExec": "wezterm",
            "trunk.trunkGrayOutNonBlockingIssues": false,
            "typescript.suggest.paths": false,
            "window.zoomLevel": 1.25 ,
            "window.menuBarVisibility": "toggle", 
            "window.restoreFullscreen": true,
            "workbench.colorTheme": "Material Theme Darker High Contrast",
            "workbench.iconTheme": "eq-material-theme-icons-darker",
            "workbench.startupEditor": "none",
            "materialTheme.accent": "Cyan",
            "workbench.colorCustomizations": {
                "[Material Theme Darker High Contrast]": {
                    "activityBarBadge.background": "#00BCD4",
                    "activityBar.activeBorder": "#00BCD4",
                    "list.activeSelectionForeground": "#00BCD4",
                    "list.inactiveSelectionForeground": "#00BCD4",
                    "list.highlightForeground": "#00BCD4",
                    "scrollbarSlider.activeBackground": "#00BCD450",
                    "editorSuggestWidget.highlightForeground": "#00BCD4",
                    "textLink.foreground": "#00BCD4",
                    "progressBar.background": "#00BCD4",
                    "pickerGroup.foreground": "#00BCD4",
                    "tab.activeBorder": "#00BCD4",
                    "notificationLink.foreground": "#00BCD4",
                    "editorWidget.resizeBorder": "#00BCD4",
                    "editorWidget.border": "#00BCD4",
                    "settings.modifiedItemIndicator": "#00BCD4",
                    "settings.headerForeground": "#00BCD4",
                    "panelTitle.activeBorder": "#00BCD4",
                    "breadcrumb.activeSelectionForeground": "#00BCD4",
                    "menu.selectionForeground": "#00BCD4",
                    "menubar.selectionForeground": "#00BCD4",
                    "editor.findMatchBorder": "#00BCD4",
                    "selection.background": "#00BCD440",
                    "statusBarItem.remoteBackground": "#00BCD4"
                }
            },
            "workbench.preferredDarkColorTheme": "Material Theme Darker High Contrast",
            "workbench.editor.decorations.colors": false,
            "workbench.editor.autoLockGroups": {
                "workbench.input.interactive": true,
                "imagePreview.previewEditor": true,
                "vscode.markdown.preview.editor": true,
                "jsProfileVisualizer.cpuprofile.table": true,
                "jsProfileVisualizer.heapprofile.table": true,
                "gitlens.rebase": true,
                "jupyter-notebook": true,
                "mainThreadWebview-markdown.preview": true
            },
            "workbench.editor.limit.enabled": true,
            "workbench.editor.limit.value": 15,
            "workbench.editor.limit.perEditorGroup": true,
            "workbench.editor.scrollToSwitchTabs": true,
            "workbench.editor.wrapTabs": true,
            "window.autoDetectHighContrast": false,


          }

