- hosts: 'workers, masters'
  become: yes

  tasks:
    - name: create the kube user account
      user:
        name: kube
        append: yes
        state: present
        createhome: yes
        shell: /bin/bash
        groups: 'wheel'

    - name: kube authorized ssh keys
      authorized_key:
        user: kube
        key: "{{ item }}"
      with_file:
        - ~/.ssh/id_rsa.pub
