---
# Usenet / SABNZBD has gotten a reputation as a piracy platform.
# Don't pirate, kids. Join the open source community instead!
# I use SABNZBD to monitor and fetch actual Linux ISOs so my VMs use the latest image.

- hosts: 'master'
  become: yes
  become_user: kube

  tasks:
    - name: Create PVC to store SABNZBD Configuration
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: sabnzbd-config
            namespace: usenet
            labels:
              app: usenet
          spec:
            storageClassName: nfs-client
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 20Mi

    - name: Create SABNZBD Deployment
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Deployment
          metadata:
            name: sabnzbd
            namespace: usenet
            labels:
              app: sabnzbd
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: sabnzbd
            template:
              metadata:
                labels:
                  app: sabnzbd
              spec:
                containers:
                - name: sabnzbd
                  image: lscr.io/linuxserver/sabnzbd:latest
                  ports:
                  - name: sabnzbd-web
                    containerPort: 8080
                  volumeMounts:
                  - name: data
                    mountPath: /downloads
                  - name: config
                    mountPath: /config
                  - name: nzbwatch
                    mountPath: /watch
                volumes:
                - name: data
                  persistentVolumeClaim:
                    claimName: storage
                - name: config
                  persistentVolumeClaim:
                    claimName: sabnzbd-config
                - name: nzbwatch
                  persistentVolumeClaim:
                    claimName: nzbwatch

    - name: Create SABNZBD Service
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            labels:
              app: sabnzbd
            namespace: usenet
            name: sabnzbd-svc
          spec:
            ports:
            - name: sabnzbd-svc-port
              port: 8080
              protocol: TCP
            selector:
              app: sabnzbd

    - name: Create SABNZBD IngressRoute
      kubernetes.core.k8s:
        definition:
          apiVersion: traefik.containo.us/v1alpha1
          kind: IngressRoute
          metadata:
            name: sabnzbd
            namespace: usenet
          spec:
            entryPoints:
              - websecure
            routes:
              - match: Host(`fetch.news.madeof.glass`)
                kind: Rule
                middlewares:
                - name: insecure-auth
                  namespace: usenet
                services:
                  - name: sabnzbd-svc
                    port: 8080
                    namespace: usenet
            tls:
              certResolver: letsencrypt

