---
- hosts: 'master'
  become: yes
  become_user: kube

  tasks:
    - name: create sabnzbd deployment
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Deployment
          metadata:
            name: sabnzbd
            namespace: usenet
            labels:
              app: sabnzbd
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: sabnzbd
            template:
              metadata:
                labels:
                  app: sabnzbd
              spec:
                containers:
                - name: sabnzbd
                  image: lscr.io/linuxserver/sabnzbd:latest
                  ports:
                  - name: sabnzbd-web
                    containerPort: 8080
                  volumeMounts:
                  - name: data
                    mountPath: /downloads
                  - name: config
                    mountPath: /config
                volumes:
                - name: data
                  persistentVolumeClaim:
                    claimName: usenet-storage
                - name: config
                  persistentVolumeClaim:
                    claimName: sabnzbd-config

    - name: create sabnzbd service
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            labels:
              app: sabnzbd
            namespace: usenet
            name: sabnzbd-svc
          spec:
            ports:
            - name: sabnzbd-svc-port
              port: 8080
              protocol: TCP
            selector:
              app: sabnzbd

    - name: create IngressRoute
      kubernetes.core.k8s:
        definition:
          apiVersion: traefik.containo.us/v1alpha1
          kind: IngressRoute
          metadata:
            name: sabnzbd
            namespace: usenet
          spec:
            entryPoints:
              - websecure
            routes:
              - match: Host(`beta.madeof.glass`)
                kind: Rule
                middlewares:
                - name: insecure-auth
                  namespace: usenet
                services:
                  - name: sabnzbd-svc
                    port: 8080
                    namespace: usenet
            tls:
              certResolver: letsencrypt
