---
- hosts: 'master'
  become: yes
  become_user: kube

  tasks:
    - name: Create metallb configuration
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            namespace: metallb-system
            name: config
          data:
            config: |
              address-pools:
              - name: default
                protocol: layer2
                addresses:
                - 10.0.0.240-10.0.0.250
