additionalArguments:
  - "--certificatesresolvers.letsencrypt.acme.email=root@madeof.glass"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
  - "--certificatesResolvers.letsencrypt.acme.dnschallenge.provider=route53"
  - "--certificatesResolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53"
  - "--api.insecure=true"
  - "--accesslog=true"
  - "--log.level=INFO"

envFrom:
  - secretRef:
      name: aws-credentials

ports:
  web:
    port: 80
    redirectTo: websecure
  websecure:
    port: 443
    tls:
      enabled: true
      options: ""
      certResolver: "letsencrypt"
      domains:
        - main: "*.madeof.glass"

service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: "10.0.10.129"

# tlsOptions:
#   default:
#     sniStrict: true
#     preferServerCipherSuites: true
#     curvePreferences:
#       - CurveP521
#       - CurveP384

persistence:
  enabled: true
  name: traefik-config
  accessMode: ReadWriteOnce
  size: 128Mi
  path: /data
  storageClass: "nfs-client"

securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0
