installation:
  calicoNetwork:
    bgp: Disabled
    ipPools:
    - cidr: 10.48.0.0/16
      encapsulation: VXLANCrossSubnet
    nodeAddressAutodetectionV4:
      interface: "e*"
      #canReach: "10.0.0.1"
    #hostPorts: Disabled


