
additionalArguments:
  - "--providers.kubernetesingress.ingressclass=traefik-internal"
  - "--api.insecure=true"
  - "--accesslog=true"
  - "--log.level=INFO"

envFrom:
  - secretRef:
      name: aws-credentials

ingressClass:
  enabled: true
  isDefaultClass: true

ports:
  web:
    port: 80
    redirectTo: websecure
  websecure:
    port: 443
    tls:
      enabled: true
      options: ""
      certResolver: "letsencrypt"
      domains:
        - main: "*.madeof.glass"

service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: "10.0.10.129"

tlsOptions:
  default:
    sniStrict: true
    preferServerCipherSuites: true
    curvePreferences:
      - CurveP521
      - CurveP384

certResolvers:
  letsencrypt:
    caServer: https://acme-staging-v02.api.letsencrypt.org/directory # demo
    email: root@madeof.glass
    dnsChallenge:
      provider: route53
      resolvers:
        - 1.1.1.1
        - 9.9.9.9
    storage: /data/acme.json

securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0
