---
- hosts: 'master'
  become: yes
  become_user: kube

  tasks:
  # Creates a usenet namespace to house usenet-related configuration
    - name: Create usenet namespace
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: usenet
            labels:
              app: usenet
