# not migrated
---

- name: Configure input devices
  hosts: localhost
  become: yes

  vars:
    bluetooth_devices:
      - D9:16:2F:1E:86:65

  tasks:
    # Removed. Apparently hardcoding an device MAC address is unreliable on Bluetooth connections, as the MAC changes.
    # Need to find a better solution.

    # - name: Bluetooth power cycle
    #   command: 'bluetoothctl power off'

    # - name: Bluetooth power cycle
    #   command: 'bluetoothctl power on'

    # - name: Bluetooth agent on
    #   command: 'bluetoothctl agent on'

    # - name: Bluetooth scan on
    #   command: 'bluetoothctl scan on'
    #   async: 60
    #   poll: 0
    #   register: bluetooth_scan
    #   ignore_errors: yes

    # - name: Pause
    #   pause:
    #     prompt: 'Enable pairing mode on bluetooth devices'

    # - name: Trust bluetooth item
    #   command: 'bluetoothctl trust {{ item }}'
    #   async: 15
    #   poll: 5
    #   ignore_errors: yes
    #   loop: '{{ bluetooth_devices }}'

    # - name: Pair with bluetooth item
    #   command: 'bluetoothctl pair {{ item }}'
    #   async: 15
    #   poll: 5
    #   ignore_errors: yes
    #   loop: '{{ bluetooth_devices }}'

    # - name: Connect with bluetooth item
    #   command: 'bluetoothctl connect {{ item }}'
    #   async: 15
    #   poll: 5
    #   ignore_errors: yes
    #   loop: '{{ bluetooth_devices }}'

    # - name: Remove bluetooth link-layer privacy on BLE
    #   community.general.ini_file:
    #     path: '/var/lib/bluetooth/F4:46:37:81:97:77/{{ item }}/info'
    #     section: IdentityResolvingKey
    #     state: absent
    #   loop: '{{ bluetooth_devices }}'

    # - name: Restart bluetooth service
    #   systemd:
    #     name: bluetooth
    #     state: restarted
