---
- hosts: 'master'
  become: yes
  become_user: kube

  tasks:
    - name: Create PV for sabnzbd config
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: sabnzbd-config
            namespace: usenet
            labels:
              app: sabnzbd
          spec:
            capacity:
              storage: 20Mi
            accessModes:
              - ReadWriteMany
            nfs:
              server: cluster.local-nfs-subdir-external-provisioner
              path: "/sabnzbd-config"
            mountOptions:
              - nfsvers=4.2

    - name: Create PVC for sabnzbd config
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: sabnzbd-config-pvc
            namespace: usenet
            labels:
              app: sabnzbd
          spec:
            storageClassName: sabnzbd-config
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 20Mi
