---
- hosts: 'master'
  become: yes
  become_user: kube

  tasks:
    - name: Create shared PVC to hold linux isos 
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: usenet-storage
            namespace: usenet
            labels:
              app: usenet
          spec:
            storageClassName: nfs-client
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 100Gi
